version: "3"

services:
  vrising:
    image: bjg96/vrising-server:latest
    container_name: vrising-server
    volumes:
      - /data/opt/vrising:/data
    ports:
      - 27015:27015/udp
      - 27016:27016/udp
    restart: unless-stopped
    tty: true
